spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/corenuts
#    username: root
#    password: root
    url: jdbc:mysql://54.64.6.102:3306/corenuts
    username: theuser
    password: Krishna@8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 7777